spring:
  application:
    name: weather Project

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigs?characterEncoding=UTF-8
    username: root
    password: root

    hikari:
      auto-commit: true
      minimum-idle: 40
      maximum-pool-size: 100
      transaction-isolation: TRANSACTION_READ_COMMITTED
      pool-name: bigs

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 50
        #show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

server:
  error:
    # 스프링 부트가 기본적으로 제공하는 Error 페이지 끄기
    whitelabel:
      enabled: false

    # 오류 페이지 기본 경로
    path: /errors/

    # Error 메시지 포함 여부
    include-exception: true
    include-message: on_param
    include-stacktrace: on_param
    include-binding-errors: on_param